server:
  # 端口号
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    # 服务名称为FEBS-Register
    name: FEBS-Register
  security:
    user:
      name: febs
      password: 123456

eureka:
  instance:
    # 指定了Eureka服务端的地址，因为我们是在本地搭建的，所以填写为localhost
    hostname: localhost
  client:
    # 表示是否将服务注册到Eureka服务端，由于我们这里是单节点的Eureka服务端，所以这里指定false；
    register-with-eureka: false
    # 表示是否从Eureka服务端获取服务信息，因为这里是单节点的Eureka服务端，并不需要从别的Eureka服务端同步服务信息，所以这里设置为false；
    fetch-registry: false
    # 微服务更新实例信息的变化到Eureka服务端的间隔时间，单位为秒，这里指定为30秒（这就是微服务启动后，要过一会才能注册到Eureka服务端的原因）。
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      # 指定Eureka服务端的地址，这里为当前项目地址 http://localhost:8001/register/eureka/
      # defaultZone: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
      defaultZone:  http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
