server:
  # 应用端口号为8201
  port: 8201

spring:
  # 关闭数据库自动装配,否则这些模块在启动的时候将抛出异常：Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    # 服务名称为FEBS-Server-System
    name: FEBS-Server-System

eureka:
  instance:
    # 向Eureka 服务端发送心跳的间隔时间，单位为秒，用于服务续约。这里配置为20秒，即每隔20秒向febs-register发送心跳，表明当前服务没有宕机；
    lease-renewal-interval-in-seconds: 20
  client:
    # 表示是否将服务注册到Eureka服务端
    register-with-eureka: true
    # 表示是否从Eureka服务端获取服务信息
    fetch-registry: true
    # 微服务更新实例信息的变化到Eureka服务端的间隔时间，单位为秒，这里指定为30秒（这就是微服务启动后，要过一会才能注册到Eureka服务端的原因）
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      # 指定Eureka服务端的地址，这里为当前项目地址 http://localhost:8001/register/eureka/
      defaultZone: http://febs:123456@localhost:8001/register/eureka/

# oauth2相关配置
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      # 路径为http://localhost:8301/auth/user，通过微服务网关，该请求将被转发到http://localhost:8101/user
      # 到认证服务器里校验当前请求头中的令牌是否为合法的令牌
      # 通过当前令牌获取对应的用户信息
      user-info-uri: http://localhost:8301/auth/user